const dummyFlights = [{ price: 123,
  arrivalDate: '2017-04-19',
  departureDate: '2017-04-28',
  originTerminal: 'EWR',
  city: 'Orlando',
  country: 'United States',
  IataCode: 'MCO',
  carrier: 'Spirit Airlines',
  imageUrl:
  ['http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg',
    'http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg',
    'http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg',
    'http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg',
    'http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg'] },
{ price: 206,
  arrivalDate: '2017-04-19',
  departureDate: '2017-04-28',
  originTerminal: 'EWR',
  city: 'Ottawa',
  country: 'Canada',
  IataCode: 'YOW',
  carrier: 'Porter Airlines',
  imageUrl:
  ['http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg',
    'http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg',
    'http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg',
    'http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg',
    'http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg'] },
{ price: 282,
  arrivalDate: '2017-04-19',
  departureDate: '2017-04-28',
  originTerminal: 'EWR',
  city: 'San Juan',
  country: 'Puerto Rico',
  IataCode: 'SJU',
  carrier: 'jetBlue',
  imageUrl:
  ['http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg',
    'http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg',
    'http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg',
    'http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg',
    'http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg'] },
{ price: 284,
  arrivalDate: '2017-04-19',
  departureDate: '2017-04-28',
  originTerminal: 'EWR',
  city: 'Toronto',
  country: 'Canada',
  IataCode: 'YTZ',
  carrier: 'Porter Airlines',
  imageUrl:
  ['http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg',
    'http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg',
    'http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg',
    'http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg',
    'http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg'] },
{ price: 285,
  arrivalDate: '2017-04-19',
  departureDate: '2017-04-28',
  originTerminal: 'EWR',
  city: 'Cancun',
  country: 'Mexico',
  IataCode: 'CUN',
  carrier: 'United',
  imageUrl:
  ['http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg',
    'http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg',
    'http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg',
    'http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg',
    'http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg'] },
{ price: 322,
  arrivalDate: '2017-04-19',
  departureDate: '2017-04-28',
  originTerminal: 'JFK',
  city: 'Havana',
  country: 'Cuba',
  IataCode: 'HAV',
  carrier: 'Aeromexico',
  imageUrl:
  ['http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg',
    'http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg',
    'http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg',
    'http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg',
    'http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg'] },
{ price: 372,
  arrivalDate: '2017-04-19',
  departureDate: '2017-04-28',
  originTerminal: 'JFK',
  city: 'Bridgetown',
  country: 'Barbados',
  IataCode: 'BGI',
  carrier: 'jetBlue',
  imageUrl: ['http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg',
    'http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg',
    'http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg',
    'http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg',
    'http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg'] },
{ price: 377,
  arrivalDate: '2017-04-19',
  departureDate: '2017-04-28',
  originTerminal: 'JFK',
  city: 'Pointe-a-Pitre',
  country: 'Guadeloupe',
  IataCode: 'PTP',
  carrier: 'Norwegian',
  imageUrl:
  ['http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg',
    'http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg',
    'http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg',
    'http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg',
    'http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg'] },
{ price: 393,
  arrivalDate: '2017-04-19',
  departureDate: '2017-04-28',
  originTerminal: 'JFK',
  city: 'Quito',
  country: 'Ecuador',
  IataCode: 'UIO',
  carrier: 'Aeromexico',
  imageUrl:
  ['http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg',
    'http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg',
    'http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg',
    'http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg',
    'http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg'] },
{ price: 399,
  arrivalDate: '2017-04-19',
  departureDate: '2017-04-28',
  originTerminal: 'LGA',
  city: 'San Jose',
  country: 'Costa Rica',
  IataCode: 'SJO',
  carrier: 'Spirit Airlines',
  imageUrl:
  ['http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg',
    'http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg',
    'http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg',
    'http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg',
    'http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg'] },
{ price: 418,
  arrivalDate: '2017-04-19',
  departureDate: '2017-04-28',
  originTerminal: 'LGA',
  city: 'Medellin',
  country: 'Colombia',
  IataCode: 'MDE',
  carrier: 'jetBlue',
  imageUrl:
  ['http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg',
    'http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg',
    'http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg',
    'http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg',
    'http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg'] },
{ price: 436,
  arrivalDate: '2017-04-19',
  departureDate: '2017-04-28',
  originTerminal: 'JFK',
  city: 'Copenhagen',
  country: 'Denmark',
  IataCode: 'CPH',
  carrier: 'Norwegian',
  imageUrl:
  ['http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg',
    'http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg',
    'http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg',
    'http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg',
    'http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg'] },
{ price: 453,
  arrivalDate: '2017-04-19',
  departureDate: '2017-04-28',
  originTerminal: 'JFK',
  city: 'Rome',
  country: 'Italy',
  IataCode: 'FCO',
  carrier: 'Royal Air Maroc',
  imageUrl:
  ['http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg',
    'http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg',
    'http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg',
    'http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg',
    'http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg'] },
{ price: 474,
  arrivalDate: '2017-04-19',
  departureDate: '2017-04-28',
  originTerminal: 'JFK',
  city: 'Samara',
  country: 'Russia',
  IataCode: 'KUF',
  carrier: 'Turkish Airlines',
  imageUrl:
  ['http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg',
    'http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg',
    'http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg',
    'http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg',
    'http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg'] },
{ price: 498,
  arrivalDate: '2017-04-19',
  departureDate: '2017-04-28',
  originTerminal: 'JFK',
  city: 'Paris',
  country: 'France',
  IataCode: 'ORY',
  carrier: 'Royal Air Maroc',
  imageUrl:
  ['http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg',
    'http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg',
    'http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg',
    'http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg',
    'http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg'] },
{ price: 508,
  arrivalDate: '2017-04-19',
  departureDate: '2017-04-28',
  originTerminal: 'JFK',
  city: 'Puerto Plata',
  country: 'Dominican Republic',
  IataCode: 'POP',
  carrier: 'jetBlue',
  imageUrl:
  ['http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg',
    'http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg',
    'http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg',
    'http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg',
    'http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg'] },
{ price: 510,
  arrivalDate: '2017-04-19',
  departureDate: '2017-04-28',
  originTerminal: 'JFK',
  city: 'Stockholm',
  country: 'Sweden',
  IataCode: 'ARN',
  carrier: 'Norwegian',
  imageUrl:
  ['http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg',
    'http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg',
    'http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg',
    'http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg',
    'http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg'] },
{ price: 513,
  arrivalDate: '2017-04-19',
  departureDate: '2017-04-28',
  originTerminal: 'JFK',
  city: 'Dublin',
  country: 'Ireland',
  IataCode: 'DUB',
  carrier: 'British Airways',
  imageUrl:
  ['http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg',
    'http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg',
    'http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg',
    'http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg',
    'http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg'] },
{ price: 515,
  arrivalDate: '2017-04-19',
  departureDate: '2017-04-28',
  originTerminal: 'JFK',
  city: 'Lisbon',
  country: 'Portugal',
  IataCode: 'LIS',
  carrier: 'Royal Air Maroc',
  imageUrl:
  ['http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg',
    'http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg',
    'http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg',
    'http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg',
    'http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg'] },
{ price: 521,
  arrivalDate: '2017-04-19',
  departureDate: '2017-04-28',
  originTerminal: 'JFK',
  city: 'Caracas',
  country: 'Venezuela',
  IataCode: 'CCS',
  carrier: 'Avianca',
  imageUrl:
  ['http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg',
    'http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg',
    'http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg',
    'http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg',
    'http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg'] },
{ price: 521,
  arrivalDate: '2017-04-19',
  departureDate: '2017-04-28',
  originTerminal: 'JFK',
  city: 'Cartagena',
  country: 'Colombia',
  IataCode: 'CTG',
  carrier: 'jetBlue',
  imageUrl:
  ['http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg',
    'http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg',
    'http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg',
    'http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg',
    'http://www.pbh2.com/wordpress/wp-content/uploads/2014/02/cute-french-bulldog-puppy.jpg'] }];

module.exports = dummyFlights;
